version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"

